type resource_type = "food"|"wood"|"magic feathers"|"fire spirits"|"ice crystals"|"orbs of darkness"|"phoenix eggs"|"fairy dust"|"dragon skin"|"copper swords"|"iron swords"|"steel swords"|"steel arrowheads"|"ice swords"|"fire swords"|"holy swords"|"frost bows"|"arcane robes"|"omni-enchanted swords"|"dragonhide armor";
type main_contract_type = "explore land in the north"|"clear out copper mine"|"explore land in the south"|"clear out iron mine"|"explore land in the east"|"clear out coal mine"|"explore land in the west"|"research steelmaking"|"research steel fletching"|"explore magma cave"|"research elemental enchantments"|"explore ice cave"|"research holy enchantment"|"open a portal to the land of the dead"|"make deal with fairies"|"research advanced enchantment techniques"|"explore mapped region"|"research dragonhide crafting"|"research dragon anatomy"|"kill dragon"|"grow kingdom";
type contract = "explore land in the north"|"clear out copper mine"|"explore land in the south"|"clear out iron mine"|"explore land in the east"|"clear out coal mine"|"explore land in the west"|"research steelmaking"|"research steel fletching"|"explore magma cave"|"research elemental enchantments"|"explore ice cave"|"research holy enchantment"|"open a portal to the land of the dead"|"make deal with fairies"|"research advanced enchantment techniques"|"explore mapped region"|"research dragonhide crafting"|"research dragon anatomy"|"kill dragon"|"grow kingdom"|"make deal with witches"|"make deal with angels"|"make some food"|"fend off invaders"|"fend off magic invaders";
type contract_state = "not signed"|"in progress"|"autocomplete"|"complete";
var resources : resource_type[]= ["food", "wood", "magic feathers", "fire spirits", "ice crystals", "orbs of darkness", "phoenix eggs", "fairy dust", "dragon skin", "copper swords", "iron swords", "steel swords", "steel arrowheads", "ice swords", "fire swords", "holy swords", "frost bows", "arcane robes", "omni-enchanted swords", "dragonhide armor"];
var main_contract : main_contract_type[] = ["explore land in the north", "clear out copper mine", "explore land in the south", "clear out iron mine", "explore land in the east", "clear out coal mine", "explore land in the west", "research steelmaking", "research steel fletching", "explore magma cave", "research elemental enchantments", "explore ice cave", "research holy enchantment", "open a portal to the land of the dead", "make deal with fairies", "research advanced enchantment techniques", "explore mapped region", "research dragonhide crafting", "research dragon anatomy", "kill dragon", "grow kingdom"]


interface game_state_interface {
  "money" : number,
  "research grant" : number,
  "worker wages" : [number, number, number],
  "workers" :  [number, number, number],
  "selling prices" : {"food": number, "wood": number, "magic feathers": number, "fire spirits": number, "ice crystals": number, "orbs of darkness": number, "phoenix eggs": number, "fairy dust": number, "dragon skin": number, "copper swords": number, "iron swords": number, "steel swords": number, "steel arrowheads": number, "ice swords": number, "fire swords": number, "holy swords": number, "frost bows": number, "arcane robes": number, "omni-enchanted swords": number, "dragonhide armor": number}, 
  "worker allocation" : {
    "building" : {
 "food" : number,
 "wood" : number,
 "magic feathers" : number,
 "fire spirits" : number,
 "ice crystals" : number,
 "orbs of darkness" : number,
 "phoenix eggs" : number,
 "fairy dust" : number,
 "dragon skin" : number,
 "copper swords" : number,
 "iron swords" : number,
 "steel swords" : number,
 "steel arrowheads" : number,
 "ice swords" : number,
 "fire swords" : number,
 "holy swords" : number,
 "frost bows" : number,
 "arcane robes" : number,
 "omni-enchanted swords" : number,
 "dragonhide armor" : number,
},
"main_contract" : {
 "explore land in the north": number,
 "clear out copper mine": number,
 "explore land in the south": number,
 "clear out iron mine": number,
 "explore land in the east": number,
 "clear out coal mine": number,
 "explore land in the west": number,
 "research steelmaking": number,
 "research steel fletching": number,
 "explore magma cave": number,
 "research elemental enchantments": number,
 "explore ice cave": number,
 "research holy enchantment": number,
 "open a portal to the land of the dead": number,
 "make deal with fairies": number,
 "research advanced enchantment techniques": number,
 "explore mapped region": number,
 "research dragonhide crafting": number,
 "research dragon anatomy": number,
 "kill dragon": number,
 "grow kingdom": number,
}
  },
  "resources" : {
 "food" :  number,
 "wood" :  number,
 "magic feathers" :  number,
 "fire spirits" :  number,
 "ice crystals" :  number,
 "orbs of darkness" :  number,
 "phoenix eggs" :  number,
 "fairy dust" :  number,
 "dragon skin" :  number,
 "copper swords" :  number,
 "iron swords" :  number,
 "steel swords" :  number,
 "steel arrowheads" :  number,
 "ice swords" :  number,
 "fire swords" :  number,
 "holy swords" :  number,
 "frost bows" :  number,
 "arcane robes" :  number,
 "omni-enchanted swords" :  number,
 "dragonhide armor" :  number,
 },
contracts :{ "explore land in the north" : contract_state,"clear out copper mine" : contract_state,"explore land in the south" : contract_state,"clear out iron mine" : contract_state,"explore land in the east" : contract_state,"clear out coal mine" : contract_state,"explore land in the west" : contract_state,"research steelmaking" : contract_state,"research steel fletching" : contract_state,"explore magma cave" : contract_state,"research elemental enchantments" : contract_state,"explore ice cave" : contract_state,"research holy enchantment" : contract_state,"open a portal to the land of the dead" : contract_state,"make deal with fairies" : contract_state,"research advanced enchantment techniques" : contract_state,"explore mapped region" : contract_state,"research dragonhide crafting" : contract_state,"research dragon anatomy" : contract_state,"kill dragon" : contract_state,"grow kingdom" : contract_state,"make deal with witches" : contract_state,"make deal with angels" : contract_state,"make some food" : contract_state,"fend off invaders" : contract_state,"fend off magic invaders" : contract_state,}, "quest progress" :{ "explore land in the north" : number,"clear out copper mine" : number,"explore land in the south" : number,"clear out iron mine" : number,"explore land in the east" : number,"clear out coal mine" : number,"explore land in the west" : number,"research steelmaking" : number,"research steel fletching" : number,"explore magma cave" : number,"research elemental enchantments" : number,"explore ice cave" : number,"research holy enchantment" : number,"open a portal to the land of the dead" : number,"make deal with fairies" : number,"research advanced enchantment techniques" : number,"explore mapped region" : number,"research dragonhide crafting" : number,"research dragon anatomy" : number,"kill dragon" : number,"grow kingdom" : number,"make deal with witches" : number,"make deal with angels" : number,"make some food" : number,"fend off invaders" : number,"fend off magic invaders" : number,} 
}

var game_state_initial : game_state_interface =  {
  "money" : 0,
  "research grant" : 0,
  "worker wages" : [0, 0, 0],
  "workers" :  [0, 0, 0],
  "selling prices" : {"food": 0, "wood": 0, "magic feathers": 0, "fire spirits": 0, "ice crystals": 0, "orbs of darkness": 0, "phoenix eggs": 0, "fairy dust": 0, "dragon skin": 0, "copper swords": 0, "iron swords": 0, "steel swords": 0, "steel arrowheads": 0, "ice swords": 0, "fire swords": 0, "holy swords": 0, "frost bows": 0, "arcane robes": 0, "omni-enchanted swords": 0, "dragonhide armor": 0}, 
  "worker allocation" : {
    "building" : {
 "food" : 0,
 "wood" : 0,
 "magic feathers" : 0,
 "fire spirits" : 0,
 "ice crystals" : 0,
 "orbs of darkness" : 0,
 "phoenix eggs" : 0,
 "fairy dust" : 0,
 "dragon skin" : 0,
 "copper swords" : 0,
 "iron swords" : 0,
 "steel swords" : 0,
 "steel arrowheads" : 0,
 "ice swords" : 0,
 "fire swords" : 0,
 "holy swords" : 0,
 "frost bows" : 0,
 "arcane robes" : 0,
 "omni-enchanted swords" : 0,
 "dragonhide armor" : 0,
},
"main_contract" : {
 "explore land in the north": 0,
 "clear out copper mine": 0,
 "explore land in the south": 0,
 "clear out iron mine": 0,
 "explore land in the east": 0,
 "clear out coal mine": 0,
 "explore land in the west": 0,
 "research steelmaking": 0,
 "research steel fletching": 0,
 "explore magma cave": 0,
 "research elemental enchantments": 0,
 "explore ice cave": 0,
 "research holy enchantment": 0,
 "open a portal to the land of the dead": 0,
 "make deal with fairies": 0,
 "research advanced enchantment techniques": 0,
 "explore mapped region": 0,
 "research dragonhide crafting": 0,
 "research dragon anatomy": 0,
 "kill dragon": 0,
 "grow kingdom": 0,
}
  },
  "resources" : {
 "food" :  0,
 "wood" :  0,
 "magic feathers" :  0,
 "fire spirits" :  0,
 "ice crystals" :  0,
 "orbs of darkness" :  0,
 "phoenix eggs" :  0,
 "fairy dust" :  0,
 "dragon skin" :  0,
 "copper swords" :  0,
 "iron swords" :  0,
 "steel swords" :  0,
 "steel arrowheads" :  0,
 "ice swords" :  0,
 "fire swords" :  0,
 "holy swords" :  0,
 "frost bows" :  0,
 "arcane robes" :  0,
 "omni-enchanted swords" :  0,
 "dragonhide armor" :  0,
 },
contracts :{ "explore land in the north" : "not signed","clear out copper mine" : "not signed","explore land in the south" : "not signed","clear out iron mine" : "not signed","explore land in the east" : "not signed","clear out coal mine" : "not signed","explore land in the west" : "not signed","research steelmaking" : "not signed","research steel fletching" : "not signed","explore magma cave" : "not signed","research elemental enchantments" : "not signed","explore ice cave" : "not signed","research holy enchantment" : "not signed","open a portal to the land of the dead" : "not signed","make deal with fairies" : "not signed","research advanced enchantment techniques" : "not signed","explore mapped region" : "not signed","research dragonhide crafting" : "not signed","research dragon anatomy" : "not signed","kill dragon" : "not signed","grow kingdom" : "not signed","make deal with witches" : "not signed","make deal with angels" : "not signed","make some food" : "not signed","fend off invaders" : "not signed","fend off magic invaders" : "not signed",}, "quest progress" :{ "explore land in the north" : 0,"clear out copper mine" : 0,"explore land in the south" : 0,"clear out iron mine" : 0,"explore land in the east" : 0,"clear out coal mine" : 0,"explore land in the west" : 0,"research steelmaking" : 0,"research steel fletching" : 0,"explore magma cave" : 0,"research elemental enchantments" : 0,"explore ice cave" : 0,"research holy enchantment" : 0,"open a portal to the land of the dead" : 0,"make deal with fairies" : 0,"research advanced enchantment techniques" : 0,"explore mapped region" : 0,"research dragonhide crafting" : 0,"research dragon anatomy" : 0,"kill dragon" : 0,"grow kingdom" : 0,"make deal with witches" : 0,"make deal with angels" : 0,"make some food" : 0,"fend off invaders" : 0,"fend off magic invaders" : 0,} 
}

game_state_initial.money =1000000;
game_state_initial["research grant"] =1000000;
game_state_initial['worker wages'] = [1000, 1100, 1200];
 export {game_state_initial, type contract, type game_state_interface, resources, main_contract,  type resource_type, type main_contract_type };